<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zendcart\Module'                        => __DIR__ . '/Module.php',
    'Zendcart\Controller\IndexController' => __DIR__ . '/src/Zendcart/Controller/IndexController.php',
    'ZendcartTest\Framework\TestCase'        => __DIR__ . '/tests/Zendcart/Framework/TestCase.php',
    'ZendcartTest\SampleTest'                => __DIR__ . '/tests/Zendcart/SampleTest.php',
);
